### ISSUE TITLE
Few bugs to fix

### ISSUE THREAD

**Issue by davidfowl** [StackExchange/Channels.WebSockets#1] opened 2016-08-31 05:56 UTC
- Over disposing https://github.com/StackExchange/Channels.WebSockets/blob/master/src/Channels.WebSockets/WebSocketServer.cs#L1398-L1405 (I need to add something for this)
- Copying data into a readablebuffer (https://github.com/StackExchange/Channels.WebSockets/blob/master/src/Channels.WebSockets/WebSocketServer.cs#L982) are you sure you have enough space to copy into?
- Should this be more graceful? https://github.com/StackExchange/Channels.WebSockets/blob/master/src/Channels.WebSockets/WebSocketServer.cs#L1258 
- GetRaw and GetInt32 here instead of converting to a string - https://github.com/StackExchange/Channels.WebSockets/blob/master/src/Channels.WebSockets/WebSocketServer.cs#L653
- Dispose the `HttpRequest` after making the socket object https://github.com/StackExchange/Channels.WebSockets/blob/master/src/Channels.WebSockets/WebSocketServer.cs#L702

**Comment by mgravell** [comment] 2016-08-31 07:02
- Over disposing

the first is not over-disposed; see just before the `return` in the success case where it nukes the things (having transferred disposal ownership to `result`:

```
            Method = Path = HttpVersion = default(ReadableBuffer);
            Headers = null;
```
- Copying data into a readable buffer
  
  ```
              if ((len + WebSocketKeySuffixBytes.Length) > buffer.Length) throw new ArgumentException("Oversized key", nameof(key));
  ```

(note that the buffer is initialized  with an `Alloc` that gives it more than enough than we need for this scratch area)
- Should this be more graceful

Yes
- GetRaw and GetInt32

Nice; will do
- Dispose the `HttpRequest` after making the socket object

No; I use it  in `CompleteHandshakeAsync`, and (oops) it _should_ be available in `OnAuthenticateAsync` . It is already disposed via `using` when I am done with it.

**Comment by mgravell** [comment] 2016-08-31 07:06
Note: a method called `uint GetInt32()` sounds... wrong. `GetUInt32()` ?

**Comment by davidfowl** [comment] 2016-08-31 08:45
> the first is not over-disposed; see just before the return in the success case where it nukes the things (having transferred disposal ownership to result:

Ah! subtle...

> (note that the buffer is initialized with an Alloc that gives it more than enough than we need for this scratch area)

The danger is that blocks are shared and you don't want to write into a slice of data you don't own. This is an interesting scenario though. Need to think through this one...

> Note: a method called uint GetInt32() sounds... wrong. GetUInt32() ?

Yea it should be Uint32 😄 .

**Comment by mgravell** [comment] 2016-08-31 08:54
But  surely if I'm writing into a chunk that I obtained via Alloc with a minimum size, I know I'm OK as long as I don't screw up the offsets? I do check that we have enough in the span from the Alloc - am I missing something?

**Comment by mgravell** [comment] 2016-08-31 08:55
if the issue is that I need to call `Ensure()`, I can do that - but I thought that was implicit from an `Alloc` with minimum size

**Comment by davidfowl** [comment] 2016-08-31 08:56
Wait, I'm blind. I thought you were writing into the _ReadableBuffer_ this is fine. 😄

**Closed as completed** 2016-09-02 21:24 UTC
